### ISSUE TITLE
XML validates where it shouldn't?

### ISSUE THREAD

**Issue by waterkip** [markov2/perl5-XML-Compile#2]
Attached is a test that should fail but succeeds with the reader. 
If we validate the XML with xmlint I see this:
```
$ xmllint --schema bug.xsd bug.xml
<?xml version="1.0"?>
<Test:bericht xmlns:Test="http://www.example.nl/Test/XML">
  <Test:stuurgegevens>:
    <Test:berichtcode>Fo03</Test:berichtcode>
  </Test:stuurgegevens>
</Test:bericht>
bug.xml:3: element stuurgegevens: Schemas validity error : Element '{http://www.example.nl/Test/XML}stuurgegevens': Character content other than whitespace is not allowed because the content type is 'element-only'.
bug.xml fails to validate
```
[bug-xml-compile-with-colon.zip](https://github.com/markov2/perl5-XML-Compile/files/2001866/bug-xml-compile-with-colon.zip)

**Comment by markov2** [comment]
The documentation of XML::Compile::Schema says:

> Be warned that the **schema is not validated**; you can develop schemas which do work well with this module, but are not valid according to W3C. In many cases, however, the translater will refuse to accept mistakes: mainly because it cannot produce valid code.

Validation is quite expensive.  The content of fields is checked, but there are quite a number of things which are simply ignored.
