### ISSUE TITLE
Undefined subroutine _date_whitespace

### ISSUE THREAD

**Issue by ferz** [markov2/perl5-XML-Compile#3]
Undefined subroutine &XML::Compile::Schema::BuiltInFacets::_date_whitespace called at XML/Compile/Schema/BuiltInFacets.pm line 100.

It seems a wrong case in function name sub _date_whiteSpace {}, it's easy to fix.

**Comment by markov2** [comment]
Thanks!   I have now released v1.62 to CPAN with your fix.
