### ISSUE TITLE
schema2example has hard-coded Perl executable path in shebang

### ISSUE THREAD

**Issue by merkys** [markov2/perl5-XML-Compile#5]
`schema2example` has `#!/home/satfoto/bin/perl` for a shebang, which requires manual editing for everyone willing to use this script. Please unify the shebang line with the rest of the scripts under `bin/`.

**Comment by markov2** [comment]
Thanks.  Will be included in release 1.64

**Comment by merkys** [comment]
Thanks a lot for prompt fix!
